window.SCRAPED_LEADS = [
  {
    "ADDRESS": "SASUN Fabrica",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars Pizza (NQS)",
    "PHONE": "",
    "RATING": "4.6",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607723124295489/"
  },
  {
    "ADDRESS": "DIAGONAL 72 # 96-92 CENTRO COMERCIAL DIVERPLAZA LOCAL 111-112, Bogotá",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Diverplaza)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607656342586365/"
  },
  {
    "ADDRESS": "McDonald's Kennedy Central",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "McDonald's (Kennedy)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607615519425535/"
  },
  {
    "ADDRESS": "KR 100 24 31 BOGOTA",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Gran Sushi DC - Fontibón",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607696595323642/"
  },
  {
    "ADDRESS": "Cra. 90a #44, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Suba Bogotá)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607669449786422/"
  },
  {
    "ADDRESS": "Cra 53 # 128C-47",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Ehomaki Sushi Wok (Colina)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607687028114426/"
  },
  {
    "ADDRESS": "Avda. Ciudad de Cali No. 19A-50/30, Bogotá, Colombia",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "McDonald's (Hayuelos)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607606237430779/"
  },
  {
    "ADDRESS": "KR 69B # 25 SUR -49",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Suri Aves 22",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607645911352314/"
  },
  {
    "ADDRESS": "Cl 15 #144, Soacha, Cundinamarca, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Lider Pollo (Soacha)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607722637757052/"
  },
  {
    "ADDRESS": "C-85 SUR, Cra. 78B #38, Kennedy, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Kennedy)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607644845999092/"
  },
  {
    "ADDRESS": "Ak. 19 #40-34, Bogotá",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Saiko Sushi (Parkway)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764608927761957684/"
  },
  {
    "ADDRESS": "Cl. 82a #94-16, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Quirigua)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607531662705654/"
  },
  {
    "ADDRESS": "Cl. 18 Sur #19, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Restrepo)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607575606428656/"
  },
  {
    "ADDRESS": "Cl. 137b #103f83, Bogotá, Colombia",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Bacon House",
    "PHONE": "",
    "RATING": "3.9",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607610666615911/"
  },
  {
    "ADDRESS": "Tv. 72f Bis #39i16, Bogotá, Colombia",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Nikoru Sushi (Kennedy)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607788857427009/"
  },
  {
    "ADDRESS": "Carrera 47 # 138 10, Bogota",
    "CATEGORIES": "Asiática",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "China Express (Colina)",
    "PHONE": "",
    "RATING": "3.7",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607535282390002/"
  },
  {
    "ADDRESS": "KR 69B # 25 SUR -49",
    "CATEGORIES": "Asiática",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "El Líder Oriental (1 Mayo)",
    "PHONE": "",
    "RATING": "4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607990607643025/"
  },
  {
    "ADDRESS": "Avenida Cll. 53 # 70 - 65, bogota",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Onion Smash Mr Glotón (Normandía)",
    "PHONE": "",
    "RATING": "4.4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607827809930167/"
  },
  {
    "ADDRESS": "Cra 24 #41-12, bogota",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Parkway)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607607747380210/"
  },
  {
    "ADDRESS": "Avenida carrera  70 # 77 A 45 bogota",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Surti Aves 22 El Original",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607543452895925/"
  },
  {
    "ADDRESS": "Little Caesars Kennedy",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars Pizza (Kennedy)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607530958064807/"
  },
  {
    "ADDRESS": "Calle 7f #78-51",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Ehomaki Sushi Wok (Castilla)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607592429782009/"
  },
  {
    "ADDRESS": "Cl. 161 #18A-35, Usaquén, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Toberin)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607626009379830/"
  },
  {
    "ADDRESS": "Cra 91 N° 139-34, Bogotá, Colombia",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "McDonald´s (Suba)",
    "PHONE": "",
    "RATING": "4.3",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607604123501571/"
  },
  {
    "ADDRESS": "Calle 170 #55a-39 Auto, Bogotá",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars Pizza (Calle 170)",
    "PHONE": "",
    "RATING": "4.4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607628165252084/"
  },
  {
    "ADDRESS": "Cra. 16c #164-82, Usaquén, Bogotá, Cundinamarca, Colombia",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Sushi Mania",
    "PHONE": "",
    "RATING": "4.6",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607601124576385/"
  },
  {
    "ADDRESS": "Carrera 50 96 23 Bogota Colombia",
    "CATEGORIES": "Asiática",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Nuevo Éxito Chino (Castellana)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607786303097212/"
  },
  {
    "ADDRESS": "Little Caesars Javeriana",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars (Javeriana)",
    "PHONE": "",
    "RATING": "4.4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607776719113409/"
  },
  {
    "ADDRESS": "Calle 53 # 25 -30  Centro Comercial Galerias, Bogotá, Cundinamarca, Colombia",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "McDonald's (Galerias)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607710994367481/"
  },
  {
    "ADDRESS": "Cl. 150c #103f-36, Suba, Bogotá",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars (Suba)",
    "PHONE": "",
    "RATING": "4.4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764610593492045810/"
  },
  {
    "ADDRESS": "Calle 53 13- 70 (local 1), Bogota",
    "CATEGORIES": "Asiática",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Lider Oriental (Chapinero)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764608318216342807/"
  },
  {
    "ADDRESS": "4.588708997887315, -74.16161181976837",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "4.588708997887315",
    "LNG": "-74.16161181976837",
    "NAME": "Little Caesars Pizza (Madelena)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607747631614564/"
  },
  {
    "ADDRESS": "Carrera 7a bis c #78h-23, bogota",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Onion Smash by Mr Glotón (Castilla)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607822718045111/"
  },
  {
    "ADDRESS": "Little Caesars Pizza Restrepo",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars Pizza (Restrepo)",
    "PHONE": "",
    "RATING": "4.5",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607584489966790/"
  },
  {
    "ADDRESS": "CARRERA 86 # 6-37 CENTRO COMERCIAL TINTAL PLAZA , Bogotá",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Tintal Plaza)",
    "PHONE": "",
    "RATING": "4.1",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607718065964013/"
  },
  {
    "ADDRESS": "Carrera 72 # 95-31 Av. Boyacá. Estación Primax",
    "CATEGORIES": "Pizza",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Little Caesars Pizza (Lagartos)",
    "PHONE": "",
    "RATING": "4.4",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607625933884621/"
  },
  {
    "ADDRESS": "Cra. 6 #25 - 05 Sur, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (20 de Julio)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607760336161152/"
  },
  {
    "ADDRESS": "Carrera 69 B N°25-12, Cl. 34 Sur, Bogotá, Cundinamarca, Colombia",
    "CATEGORIES": "Hamburguesa",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "McDonald´s (Primera de Mayo)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607622528107579/"
  },
  {
    "ADDRESS": "Av Calle 53 #70d-55 Local 3",
    "CATEGORIES": "Sushi",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "Ehomaki Sushi Wok (Normandia)",
    "PHONE": "",
    "RATING": "4.6",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764608072161690519/"
  },
  {
    "ADDRESS": "Cl. 68a Sur #78j-68, Bogotá, Colombia",
    "CATEGORIES": "Pollo & Alitas",
    "COMPANYNAME": "DiDi Food",
    "LAT": "",
    "LNG": "",
    "NAME": "KFC (Bosa Piamonte)",
    "PHONE": "",
    "RATING": "4.2",
    "REVIEWS": "0",
    "URL": "https://web.didiglobal.com/co/food/bogota/menu-eats/5764607727536703913/"
  }
];